package com.event.business.model;

import java.io.Serializable;
import java.util.List;

import javax.validation.constraints.Pattern;

import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.NotEmpty;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "BusinessDetails")
public class BusinessDetails implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String businessId;
	@NotEmpty(message = "businessName is mandatory")
	private String businessName;
	@NotEmpty(message = "businessType is mandatory")
	private String businessType;

	@Pattern(regexp="($[0-9] {10})")
	private String primaryPhoneNumber;
	
	@Pattern(regexp="($[0-9] {10})")
	private String secondaryPhoneNumber;
	
	@Pattern(regexp="($[0-9] {10})")
	private String phoneNumber;

	@NotEmpty(message = "UserName is mandatory")
	private String userName;

	@NotEmpty(message = "FirstName is mandatory")
	private String firstName;

	@NotEmpty(message = "lastName is mandatory")
	private String lastName;

	@NotEmpty(message = "email is mandatory")
	@Email
	private String email;

	@NotEmpty(message = "websiteUrl is mandatory")
	private String websiteUrl;

	private String businessEstDate;

	private TransactionDetails transaction;

	private String businessDescription;

	private List<Service> servicesProvided;

	@NotEmpty(message = "password is mandatory")
	private String password;

	private String addressType;

	@NotEmpty(message = "addressLine1 is mandatory")
	private String addressLine1;

	@NotEmpty(message = "addressLine2 is mandatory")
	private String addressLine2;

	@NotEmpty(message = "city is mandatory")
	private String city;

	@NotEmpty(message = "state is mandatory")
	private String state;

	@NotEmpty(message = "zipCode is mandatory")
	private String zipCode;

	@NotEmpty(message = "landmark is mandatory")
	private String landmark;

	@NotEmpty(message = "country is mandatory")
	private String country;
	
	@NotEmpty(message = "secondaryAddressLine1 is mandatory")
	private String secondaryAddressLine1;

	@NotEmpty(message = "secondaryAddressLine2 is mandatory")
	private String secondaryAddressLine2;

	@NotEmpty(message = "secondaryCity is mandatory")
	private String secondaryCity;

	@NotEmpty(message = "secondaryState is mandatory")
	private String secondaryState;

	@NotEmpty(message = "secondaryZipCode is mandatory")
	private String secondaryZipCode;

	@NotEmpty(message = "secondaryLandmark is mandatory")
	private String secondaryLandmark;

	@NotEmpty(message = "secondaryCountry is mandatory")
	private String secondaryCountry;

	@DynamoDBHashKey(attributeName = "businessId")
	@DynamoDBAutoGeneratedKey
	public String getBusinessId() {
		return businessId;
	}

	public void setBusinessId(String businessId) {
		this.businessId = businessId;
	}

	@DynamoDBAttribute
	public String getBusinessName() {
		return businessName;
	}

	public void setBusinessName(String businessName) {
		this.businessName = businessName;
	}

	@DynamoDBAttribute
	public String getBusinessType() {
		return businessType;
	}

	public void setBusinessType(String businessType) {
		this.businessType = businessType;
	}
	
	@DynamoDBAttribute
	public String getPrimaryPhoneNumber() {
		return primaryPhoneNumber;
	}

	public void setPrimaryPhoneNumber(String primaryPhoneNumber) {
		this.primaryPhoneNumber = primaryPhoneNumber;
	}
	
	@DynamoDBAttribute
	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@DynamoDBAttribute
	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@DynamoDBAttribute
	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@DynamoDBAttribute
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@DynamoDBAttribute
	public String getWebsiteUrl() {
		return websiteUrl;
	}

	public void setWebsiteUrl(String websiteUrl) {
		this.websiteUrl = websiteUrl;
	}

	@DynamoDBAttribute
	public String getBusinessEstDate() {
		return businessEstDate;
	}

	public void setBusinessEstDate(String businessEstDate) {
		this.businessEstDate = businessEstDate;
	}

	@DynamoDBAttribute
	public String getBusinessDescription() {
		return businessDescription;
	}

	public void setBusinessDescription(String businessDescription) {
		this.businessDescription = businessDescription;
	}

	public List<Service> getServicesProvided() {
		return servicesProvided;
	}

	public void setServicesProvided(List<Service> servicesProvided) {
		this.servicesProvided = servicesProvided;
	}

	@DynamoDBAttribute
	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public TransactionDetails getTransaction() {
		return transaction;
	}

	public void setTransaction(TransactionDetails transaction) {
		this.transaction = transaction;
	}

	@DynamoDBAttribute
	public String getAddressType() {
		return addressType;
	}

	public void setAddressType(String addressType) {
		this.addressType = addressType;
	}

	@DynamoDBAttribute
	public String getAddressLine1() {
		return addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	@DynamoDBAttribute
	public String getAddressLine2() {
		return addressLine2;
	}

	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	@DynamoDBAttribute
	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@DynamoDBAttribute
	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@DynamoDBAttribute
	public String getZipCode() {
		return zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	@DynamoDBAttribute
	public String getLandmark() {
		return landmark;
	}

	public void setLandmark(String landmark) {
		this.landmark = landmark;
	}

	@DynamoDBAttribute
	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@DynamoDBAttribute
	public String getSecondaryAddressLine1() {
		return secondaryAddressLine1;
	}

	public void setSecondaryAddressLine1(String secondaryAddressLine1) {
		this.secondaryAddressLine1 = secondaryAddressLine1;
	}

	@DynamoDBAttribute
	public String getSecondaryAddressLine2() {
		return secondaryAddressLine2;
	}

	public void setSecondaryAddressLine2(String secondaryAddressLine2) {
		this.secondaryAddressLine2 = secondaryAddressLine2;
	}

	@DynamoDBAttribute
	public String getSecondaryCity() {
		return secondaryCity;
	}

	public void setSecondaryCity(String secondaryCity) {
		this.secondaryCity = secondaryCity;
	}

	@DynamoDBAttribute
	public String getSecondaryState() {
		return secondaryState;
	}

	public void setSecondaryState(String secondaryState) {
		this.secondaryState = secondaryState;
	}

	@DynamoDBAttribute
	public String getSecondaryZipCode() {
		return secondaryZipCode;
	}

	public void setSecondaryZipCode(String secondaryZipCode) {
		this.secondaryZipCode = secondaryZipCode;
	}

	@DynamoDBAttribute
	public String getSecondaryLandmark() {
		return secondaryLandmark;
	}

	public void setSecondaryLandmark(String secondaryLandmark) {
		this.secondaryLandmark = secondaryLandmark;
	}

	@DynamoDBAttribute
	public String getSecondaryCountry() {
		return secondaryCountry;
	}

	public void setSecondaryCountry(String secondaryCountry) {
		this.secondaryCountry = secondaryCountry;
	}

	@DynamoDBAttribute
	public String getSecondaryPhoneNumber() {
		return secondaryPhoneNumber;
	}

	public void setSecondaryPhoneNumber(String secondaryPhoneNumber) {
		this.secondaryPhoneNumber = secondaryPhoneNumber;
	}

	@DynamoDBAttribute
	public String getPhoneNumber() {
		return phoneNumber;
	}

	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}
	

}
