package com.event.business.model;

import java.io.Serializable;
import java.util.List;

import javax.validation.constraints.NotEmpty;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName= "BusinessDetails")
public class BusinessDetails implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	
	private String businessId;
    @NotEmpty(message = "businessName is mandatory")
	private String businessName;
	@NotEmpty(message = "businessType is mandatory")
	private String businessType;
	
	private Phone phone;
	
	private Address address;
	@NotEmpty(message = "UserName is mandatory")
	private String userName;
	@NotEmpty(message = "FirstName is mandatory")
	private String firstName;
	@NotEmpty(message = "lastName is mandatory")
	private String lastName;
	@NotEmpty(message = "email is mandatory")
	private String email;
	@NotEmpty(message = "websiteUrl is mandatory")
	private String websiteUrl;
	
	private String businessEstDate;
	
	private TransactionDetails transaction;
	
	private String businessDescription;
	
	private List<Service> servicesProvided;
	
	
	@NotEmpty(message = "password is mandatory")
	private String password;
		
	@DynamoDBHashKey(attributeName = "businessId")
    @DynamoDBAutoGeneratedKey
	public String getBusinessId() {
		return businessId;
	}

	public void setBusinessId(String businessId) {
		this.businessId = businessId;
	}

	@DynamoDBAttribute
	public String getBusinessName() {
		return businessName;
	}

	public void setBusinessName(String businessName) {
		this.businessName = businessName;
	}

	@DynamoDBAttribute
	public String getBusinessType() {
		return businessType;
	}

	public void setBusinessType(String businessType) {
		this.businessType = businessType;
	}

	
	public Phone getPhone() {
		return phone;
	}

	public void setPhone(Phone phone) {
		this.phone = phone;
	}

	public Address getAddress() {
		return address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	@DynamoDBAttribute
	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@DynamoDBAttribute
	public String getFirstName() {
		return firstName;
	}

	public void setFistName(String firstName) {
		this.firstName = firstName;
	}

	@DynamoDBAttribute
	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@DynamoDBAttribute
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
	
	@DynamoDBAttribute
	public String getWebsiteUrl() {
		return websiteUrl;
	}

	public void setWebsiteUrl(String websiteUrl) {
		this.websiteUrl = websiteUrl;
	}
	
	@DynamoDBAttribute
	public String getBusinessEstDate() {
		return businessEstDate;
	}

	public void setBusinessEstDate(String businessEstDate) {
		this.businessEstDate = businessEstDate;
	}


    @DynamoDBAttribute
	public String getBusinessDescription() {
		return businessDescription;
	}

	public void setBusinessDescription(String businessDescription) {
		this.businessDescription = businessDescription;
	}

	public List<Service> getServicesProvided() {
		return servicesProvided;
	}

	public void setServicesProvided(List<Service> servicesProvided) {
		this.servicesProvided = servicesProvided;
	}









	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public TransactionDetails getTransaction() {
		return transaction;
	}

	public void setTransaction(TransactionDetails transaction) {
		this.transaction = transaction;
	}
	
	
	
	
	
	
}
