package com.event.business.model;

import java.io.Serializable;
import java.util.List;

import javax.validation.constraints.Pattern;

import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.NotEmpty;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "BusinessDetails")
public class BusinessDetails implements Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String businessId;
	@NotEmpty(message = "businessName is mandatory")
	private String businessName;
	@NotEmpty(message = "businessType is mandatory")
	private String businessType;

	@Pattern(regexp="(^$|[0-9] {10})")
	private String primaryPhoneNumber;
	
	@Pattern(regexp="($[0-9] {10})")
	private String SecondaryPhoneNumber;

	@NotEmpty(message = "UserName is mandatory")
	private String userName;

	@NotEmpty(message = "FirstName is mandatory")
	private String firstName;

	@NotEmpty(message = "lastName is mandatory")
	private String lastName;

	@NotEmpty(message = "email is mandatory")
	@Email
	private String email;

	@NotEmpty(message = "websiteUrl is mandatory")
	private String websiteUrl;

	private String businessEstDate;

	private TransactionDetails transaction;

	private String businessDescription;

	private List<Service> servicesProvided;

	@NotEmpty(message = "password is mandatory")
	private String password;

	private String addressType;

	private String addressLine1;

	private String addressLine2;

	private String city;

	private String state;

	private String zipCode;

	private String landmark;

	private String country;
	
	private String secondary_addressLine1;

	private String secondary_addressLine2;

	private String secondary_city;

	private String secondary_state;

	private String secondary_zipCode;

	private String secondary_landmark;

	private String secondary_country;

	@DynamoDBHashKey(attributeName = "businessId")
	@DynamoDBAutoGeneratedKey
	public String getBusinessId() {
		return businessId;
	}

	public void setBusinessId(String businessId) {
		this.businessId = businessId;
	}

	@DynamoDBAttribute
	public String getBusinessName() {
		return businessName;
	}

	public void setBusinessName(String businessName) {
		this.businessName = businessName;
	}

	@DynamoDBAttribute
	public String getBusinessType() {
		return businessType;
	}

	public void setBusinessType(String businessType) {
		this.businessType = businessType;
	}
	
	@DynamoDBAttribute
	public String getPrimaryPhoneNumber() {
		return primaryPhoneNumber;
	}

	public void setPrimaryPhoneNumber(String primaryPhoneNumber) {
		this.primaryPhoneNumber = primaryPhoneNumber;
	}

	@DynamoDBAttribute
	public String getSecondaryPhoneNumber() {
		return SecondaryPhoneNumber;
	}

	public void setSecondaryPhoneNumber(String secondaryPhoneNumber) {
		SecondaryPhoneNumber = secondaryPhoneNumber;
	}

	@DynamoDBAttribute
	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@DynamoDBAttribute
	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@DynamoDBAttribute
	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@DynamoDBAttribute
	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@DynamoDBAttribute
	public String getWebsiteUrl() {
		return websiteUrl;
	}

	public void setWebsiteUrl(String websiteUrl) {
		this.websiteUrl = websiteUrl;
	}

	@DynamoDBAttribute
	public String getBusinessEstDate() {
		return businessEstDate;
	}

	public void setBusinessEstDate(String businessEstDate) {
		this.businessEstDate = businessEstDate;
	}

	@DynamoDBAttribute
	public String getBusinessDescription() {
		return businessDescription;
	}

	public void setBusinessDescription(String businessDescription) {
		this.businessDescription = businessDescription;
	}

	public List<Service> getServicesProvided() {
		return servicesProvided;
	}

	public void setServicesProvided(List<Service> servicesProvided) {
		this.servicesProvided = servicesProvided;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public TransactionDetails getTransaction() {
		return transaction;
	}

	public void setTransaction(TransactionDetails transaction) {
		this.transaction = transaction;
	}

	@DynamoDBAttribute
	public String getAddressType() {
		return addressType;
	}

	public void setAddressType(String addressType) {
		this.addressType = addressType;
	}

	@DynamoDBAttribute
	public String getAddressLine1() {
		return addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	@DynamoDBAttribute
	public String getAddressLine2() {
		return addressLine2;
	}

	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	@DynamoDBAttribute
	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@DynamoDBAttribute
	public String getState() {
		return state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@DynamoDBAttribute
	public String getZipCode() {
		return zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	@DynamoDBAttribute
	public String getLandmark() {
		return landmark;
	}

	public void setLandmark(String landmark) {
		this.landmark = landmark;
	}

	@DynamoDBAttribute
	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@DynamoDBAttribute
	public String getSecondary_addressLine1() {
		return secondary_addressLine1;
	}

	public void setSecondary_addressLine1(String secondary_addressLine1) {
		this.secondary_addressLine1 = secondary_addressLine1;
	}
	
	@DynamoDBAttribute
	public String getSecondary_addressLine2() {
		return secondary_addressLine2;
	}

	public void setSecondary_addressLine2(String secondary_addressLine2) {
		this.secondary_addressLine2 = secondary_addressLine2;
	}

	@DynamoDBAttribute
	public String getSecondary_city() {
		return secondary_city;
	}

	public void setSecondary_city(String secondary_city) {
		this.secondary_city = secondary_city;
	}

	@DynamoDBAttribute
	public String getSecondary_state() {
		return secondary_state;
	}

	public void setSecondary_state(String secondary_state) {
		this.secondary_state = secondary_state;
	}

	@DynamoDBAttribute	
	public String getSecondary_zipCode() {
		return secondary_zipCode;
	}

	public void setSecondary_zipCode(String secondary_zipCode) {
		this.secondary_zipCode = secondary_zipCode;
	}

	@DynamoDBAttribute	
	public String getSecondary_landmark() {
		return secondary_landmark;
	}

	public void setSecondary_landmark(String secondary_landmark) {
		this.secondary_landmark = secondary_landmark;
	}

	@DynamoDBAttribute	
	public String getSecondary_country() {
		return secondary_country;
	}

	public void setSecondary_country(String secondary_country) {
		this.secondary_country = secondary_country;
	}
	

}
