package com.event.business.model;

import java.io.Serializable;
import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName= "LoginDetails")
public class LoginDetails implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String loginDetailsId;
	
	private String emailId;
	
	private String password;
	
	private Date lastLogin;
	
	private String userName;
	
	private TransactionDetails transaction;

	@DynamoDBHashKey(attributeName = "loginDetailsId")
    @DynamoDBAutoGeneratedKey
	public String getLoginDetailsId() {
		return loginDetailsId;
	}

	public void setLoginDetailsId(String loginDetailsId) {
		this.loginDetailsId = loginDetailsId;
	}
	
	@DynamoDBAttribute(attributeName = "userName")
	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@DynamoDBAttribute
	public String getEmailId() {
		return emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	@DynamoDBAttribute
	public String getPassword() {
		return password;
	}



	public void setPassword(String password) {
		this.password = password;
	}

	public TransactionDetails getTransaction() {
		return transaction;
	}

	public void setTransaction(TransactionDetails transaction) {
		this.transaction = transaction;
	}
    
	@DynamoDBAttribute
	public Date getLastLogin() {
		return lastLogin;
	}

	public void setLastLogin(Date lastLogin) {
		this.lastLogin = lastLogin;
	}
	
}
